name: Docker Image CI

on:
  push:
    branches: [ "main", "CI/CD" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag chore-no-more:$(date +%s) chore-no-more
